@startuml

' --------v-v-v-v-v-v-v-v--------
' https://www.rijkshuisstijl.nl/organisatiespecifieke-richtlijnen/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/deelidentiteit-kerndepartement-bzk
' https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
'
' # Communicatiekleuren
' Het kerndepartement van BZK heeft uit het kleurenpalet van de rijkshuisstijl drie kleuren (elk met tint1 / tint2) gekozen:
' - Rijksoverheid hemelblauw #007bc7 (#b2d7ee/#d9ebf7)
' - Rijksoverheid rood #d52b1e (#f2bfbb/#f9dfdd)
' - Rijksoverheid groen #39870c (#c3dbb6/#e1eddb)
' Het gebruik van deze kleuren in combinatie met veel wit wordt gestimuleerd.
'
' # Tinten voor achtergrondkaders, grafieken en tabellen
' Voor achtergrondkaders, grafieken en tabellen kunnen 7 neutrale grijstinten of tinten van een communicatiekleur in stappen van 20% worden toegepast. Voor tekstachtergrond wordt grijstint1 of communicatiekleur tint2 aanbevolen om aan de contrasteisen voor een goede leesbaarheid te voldoen.
'
' Rijksoverheid grijs 1 #f3f3f3
' Rijksoverheid grijs 2 #e6e6e6
' Rijksoverheid grijs 3 #cccccc
' Rijksoverheid grijs 4 #b4b4b4
' Rijksoverheid grijs 5 #999999
' Rijksoverheid grijs 6 #696969
' Rijksoverheid grijs 7 #535353

' skinparam linetype ortho
' skinparam linetype polyline
' --------^-^-^-^-^-^-^-^--------

skinparam WrapWidth 165

skinparam Shadowing false

skinparam classAttributeIconSize 0

skinparam class {
    ArrowColor #39870c
'     ArrowMessageAlignment center
    ArrowThickness 1.5
    BackgroundColor #ffffff
    BorderColor #007bc7
    BorderColor<<extern>> #999999
    FontColor<<extern>> #999999
'     FontName RijksoverheidSansText
'     StereotypeFontStyle italic
}

skinparam note {
    BackgroundColor #fdf6bb
    BorderColor #f9e11e
    FontColor #01689b
'     FontName RijksoverheidSansText
}

skinparam package {
    BackgroundColor #f3f3f3
    BorderColor #d52b1e
    FontColor #d52b1e
'     FontName RijksoverheidSansText
    FontStyle normal
    Style rectangle
}

hide empty members

hide circle

hide stereotype

' hide AbstractObject

hide MetaObject

package "FYSIEK" {
    class AbstractBouwwerk {
    }
    class Gebouw {
    }
    class Bouwwerk {
    }
    class Bouwwerkdeel {
    }
}

package "FUNCTIE" {
    package "Gebruik" #e6e6e6 {
        class AbstractGebruik {
        }
        class Gebruikseenheid {
        }
        class Voorziening {
        }
        note top of Gebruikseenheid : Relevant voor de context van WOZ.
    }
    package "Indeling" #e6e6e6 {
        class AbstractIndeling {
        }
        class Verblijfseenheid {
        }
        note top of Verblijfseenheid : Als een verblijfsobject uit BAG, maar altijd binnendoor bereikbaar en zonder gebruiksdoel en daarom zonder eis van voorzieningen.

    }
    package "Vindbaarheid" #e6e6e6 {
        class Toegang {
        }
        class Verdieping {
        }
    }
}

' package "Representatie" {
'     class AbstractRepresentatie {
'     }
'     class GebouwRepresentatie {
'     }
'     class GebruikseenheidRepresentatie {
'     }
' '     class VerblijfseenheidRepresentatie {
' '     }
' }

' together {
'     class AbstractObject
'     class MetaObject
' }

' together {
'     class Adres
'     class Bouwbesluit
' }

' together {
'     class AbstractBouwwerk
'     class Bouwwerk
'     class Bouwwerkdeel
' }

' together {
'     class Gebruikseenheid
'     class Verblijfseenheid
' }

' together {
'     class Verblijfseenheid
'     class Verdieping
' }

AbstractObject <|-- AbstractBouwwerk
AbstractObject <|-- AbstractIndeling
AbstractObject <|-- Gebouw
AbstractObject <|-- AbstractGebruik
AbstractObject "1" <- "1..*" MetaObject
AbstractGebruik <|-- Gebruikseenheid
AbstractGebruik <|-- Voorziening
AbstractBouwwerk <|-- Bouwwerk
AbstractBouwwerk <|-- Bouwwerkdeel
Gebouw "1" *-- "1..*" Bouwwerk
Gebruikseenheid "*" --> "*" Voorziening : gebruikt
Bouwwerk "1" *-- "1..*" Bouwwerkdeel
Gebruikseenheid "*" --> "1..*" Gebouw : ligt\nin
Gebruikseenheid "1" o-- "*" Verblijfseenheid
Bouwwerk "*" <-- "*" Voorziening : ligt\nin
Bouwwerk "*" -- "1..*" Bouwbesluit : is\ngebouwd\nvolgens
Verblijfseenheid "*" <-- "*" Voorziening : ligt\nin
Verblijfseenheid "*" --> "1..*" Verdieping : ligt\nop
AbstractIndeling <|-- Verdieping
AbstractIndeling <|-- Verblijfseenheid
Gebouw "1" *-- "*" AbstractIndeling
Gebruikseenheid "1" --> "+ hoofdtoegang\nmet adres\n1" Toegang : heeft
Gebruikseenheid "*" --> "*" Verdieping : ligt\nop
Verblijfseenheid "1" --> "*" Toegang : heeft
Toegang "1" --> "0..1" Adres : heeft
' Gebouw "1" <|-- "1..*" GebouwRepresentatie
' AbstractRepresentatie <|-- GebouwRepresentatie
' Gebruikseenheid "1" <|-- "1..*" GebruikseenheidRepresentatie
' AbstractRepresentatie <|-- GebruikseenheidRepresentatie
' ' Verblijfseenheid "1" <|-- "1..*" VerblijfseenheidRepresentatie
' ' AbstractRepresentatie <|-- VerblijfseenheidRepresentatie

abstract class AbstractBouwwerk << Objecttype >> {
'     ..
    Een aaneengesloten en in één keer gerealiseerde bouwkundige constructie, ongeacht de bereikbaarheid binnendoor.
}

abstract class AbstractGebruik << Objecttype >> {
'     ..
    Kleinste ondeelbare functionele eenheid van gebruik.
}

abstract class AbstractObject << Objecttype >> {
    + identificatie
    + documentdatum
    + documentnummer
    + geconstateerd
    + status
'     ..
}

abstract class AbstractIndeling << Objecttype >> {
    + geometrie
    ..
    Gedeelte van een gebouw.
}

class Adres << extern >> {
}

class Bouwwerk << Objecttype >> {
    + bouwgeometrie [0..1]
    + bouwjaar [1..1]
'     + opleverdatum [1..1]
    + sloopgeometrie [0..1]
    + vigerendBouwbesluit [1..1]
    ..
    Grootst mogelijke geheel van een bouwkundige constructie.
}

class Bouwwerkdeel << Objecttype >> << vrijwillig >> {
    + typeConstructie: TypeConstructie [1..1]
    ..
    Bouwkundig-constructief homogeen gedeelte van een bouwwerk.
}

note bottom of Bouwwerkdeel : Schrappen indien niet relevant voor de contexten van WOZ en OOV.

class Gebouw << Objecttype >> {
    + typeGebouw: TypeGebouw [1..*]
    ..
    Grootst mogelijke homogene en tezamen duurzaam met de aarde verbonden geheel van aaneengesloten bouwwerken waarop de kleinst mogelijke verscheidenheid van attribuutwaarden integraal van toepassing is, ongeacht de bereikbaarheid binnendoor.
}

class Gebruikseenheid << Objecttype >> {
    + feitelijkGebruik
    + gebruiksdoel: Gebruiksdoel [1..*]
    + vergundGebruik
    ..
    Samenstel van alle verblijfseenheden en gebouwen die als geheel worden gebruikt.
}

class MetaObject << extern >> {
'     + typeMetagegeven: TypeMetagegeven
'     + waarde
'     ..
}

class Bouwbesluit << extern >> {
}

class Toegang << Objecttype >> {
    + geometrie
    + toegankelijkheid
    ..
    Deur of andere voorziening die toegang geeft tot een verblijfseenheid.
}

class Verblijfseenheid << Objecttype >> {
    + oppervlakte
    ..
    Kleinste binnen een gebouw gelegen aaneengesloten eenheid van gebruik die volledig binnendoor bereikbaar is en ontsloten wordt via een eigen toegang vanaf de openbare weg, een erf of een gedeelde verkeersruimte, onderwerp kan zijn van goederenrechtelijke rechtshandelingen en in functioneel opzicht zelfstandig is.
}

' --------v-v-v-v-v-v-v-v--------
' abstract class AbstractRepresentatie << Objecttype >> {
'     + geometrie
'     + levelOfDetail: LevelOfDetail [1..1]
'     + schaal: Schaalbereik [1..1]
'     ..
'     Authentieke gegeneraliseerde representatie van een object.
' }
'
' class GebouwRepresentatie << Objecttype >> {
'     ..
'     Authentieke gegeneraliseerde representatie van een gebouw.
' }
'
' ' class VerblijfseenheidRepresentatie << Objecttype >> {
' '     ..
' '     Authentieke gegeneraliseerde representatie van een verblijfseenheid.
' ' }
'
' class GebruikseenheidRepresentatie << Objecttype >> {
'     ..
'     Authentieke gegeneraliseerde representatie van een gebruikseenheid.
' }
' --------^-^-^-^-^-^-^-^--------

class Verdieping << Objecttype >> <<vrijwillig>> {
    + verdiepingsaanduiding
    ..
    Grootste aaneengesloten gedeelte van een gebouw dat zich op dezelfde bouwlaag bevindt.
}

note bottom of Verdieping : Schrappen indien niet relevant voor de contexten van WOZ en OOV.

class Voorziening << Objecttype >> {
'     + gedeeldeVoorziening
'     + geometrie
    + typeVoorziening: TypeVoorziening
    ..
    Kleinste geheel van een installatie of andere voorziening die relevant is voor een of meer gebruikseenheden.
}

note bottom of Voorziening : Relevant bij het interpreteren van objecten voor de contexten van BAG, WOZ en OOV.

@enduml
