@startuml

' --------v-v-v-v-v-v-v-v--------
' https://www.rijkshuisstijl.nl/organisatiespecifieke-richtlijnen/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/deelidentiteit-kerndepartement-bzk
' https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
'
' # Communicatiekleuren
' Het kerndepartement van BZK heeft uit het kleurenpalet van de rijkshuisstijl drie kleuren (elk met tint1 / tint2) gekozen:
' - Rijksoverheid hemelblauw #007bc7 (#b2d7ee/#d9ebf7)
' - Rijksoverheid rood #d52b1e (#f2bfbb/#f9dfdd)
' - Rijksoverheid groen #39870c (#c3dbb6/#e1eddb)
' Het gebruik van deze kleuren in combinatie met veel wit wordt gestimuleerd.
'
' # Tinten voor achtergrondkaders, grafieken en tabellen
' Voor achtergrondkaders, grafieken en tabellen kunnen 7 neutrale grijstinten of tinten van een communicatiekleur in stappen van 20% worden toegepast. Voor tekstachtergrond wordt grijstint1 of communicatiekleur tint2 aanbevolen om aan de contrasteisen voor een goede leesbaarheid te voldoen.
'
' Rijksoverheid grijs 1 #f3f3f3
' Rijksoverheid grijs 2 #e6e6e6
' Rijksoverheid grijs 3 #cccccc
' Rijksoverheid grijs 4 #b4b4b4
' Rijksoverheid grijs 5 #999999
' Rijksoverheid grijs 6 #696969
' Rijksoverheid grijs 7 #535353

' --------^-^-^-^-^-^-^-^--------

skinparam defaultFontColor black
skinparam defaultFontName Lucida Sans
skinparam defaultFontSize 11
skinparam defaultFontStyle normal
skinparam defaultMonospacedFontName Lucida Sans Typewriter
' skinparam defaultTextAlignment left
' skinparam lineType ortho
' skinparam lineType polyline
skinparam shadowing false
skinparam wrapWidth 165

skinparam class {
    ArrowColor #39870c
    ArrowFontSize 10
'     ArrowTextAlignment center
    ArrowThickness 1.5
    AttributeIconSize 0
    BackgroundColor #ffffff
    BorderColor #007bc7
'     StereotypeFontStyle italic
}

skinparam class<<extern>> {
    BorderColor #b4b4b4
    FontColor #b4b4b4
}

skinparam note {
    BackgroundColor #fdf6bb
    BorderColor #f9e11e
    FontColor #01689b
}

skinparam package {
    BackgroundColor #f3f3f3
    BorderColor #d52b1e
    FontColor #d52b1e
    FontStyle bold
    Style rectangle
}

skinparam package<< subpackage >> {
    BackgroundColor #e6e6e6
    BorderColor #e6e6e6
    FontStyle normal
}

' hide AbstractObject

hide circle

hide empty members

hide stereotype

package "FUNCTIE" {
    class Gebruikseenheid {
    }
'     note top of Gebruikseenheid : Vragen om uit te werken:\n- Hoe een woning te herkennen die alleen bereikbaar is via een winkel?\n- Welke dakkapel hoort bij welke gebruikseenheid?\n- Hoe een serre te herkennen?\n- Hoe gebruikseenheden afbakenen binnen een bedrijfsverzamelgebouw?
}

package "FYSIEK" {
    package "Gebeurtenis" << subpackage >> {
        class Bouwwerk {
        }
    }
    class Bouwblok {
    }
'     note left of Bouwblok : Na een muurdoorbraak kan een verblijfseenheid in meerdere aangrenzende gebouwen met verschillende typeGebouw zijn gelegen.
    class Gebouw {
    }
    class Toegang {
    }
    class Voorziening {
    }
    package "Indeling" << subpackage >> {
        class Bouwlaag {
        }
        class Verblijfseenheid {
        }
'         note top of Verblijfseenheid : Als een verblijfsobject uit BAG, maar altijd binnendoor bereikbaar en zonder gebruiksdoel en daarom zonder eis van voorzieningen.
    }
}

AbstractObject <|-- Bouwwerk
AbstractObject <|-- Bouwblok
AbstractObject <|-- Gebouw
AbstractObject <|-- Gebruikseenheid
AbstractObject <|-- Voorziening
Gebouw "1..*" o-- "1..*" Bouwwerk
Gebruikseenheid "*" -> "*" Vastgoed : gebruikt
Gebruikseenheid "*" --> "*" Voorziening : gebruikt
Gebruikseenheid "*" --> "1..*" Gebouw : gebruikt
Gebruikseenheid "1" o-- "*" Verblijfseenheid
Bouwwerk "1..*" o-- "*" Voorziening
Bouwblok "1" *- "1..*" Gebouw
Bouwwerk "*" .. "1..*" Bouwbesluit : is\ngebouwd\nvolgens
Verblijfseenheid "*" --> "*" Voorziening : heeft
Bouwlaag "*" --> "*" Voorziening : omvat
Verblijfseenheid "*" --> "1..*" Bouwlaag : ligt\nop
AbstractObject <|-- Bouwlaag
AbstractObject <|-- Verblijfseenheid
Bouwblok "1" *-- "*" Verblijfseenheid
Gebouw "1" *-- "1..*" Bouwlaag
' Gebouw "*" --> "*" "IFC-model" : is\nbeschreven\nin
Bouwwerk "1..*" -> "1" "IFC-model" : is\nbeschreven\nin
Gebruikseenheid "1" --> "+ hoofdtoegang\nmet adres 1" Toegang : gebruikt
Gebruikseenheid "*" --> "*" Bouwlaag : ligt\nop
Verblijfseenheid "1" --> "1..*" Toegang : heeft
Toegang "1" --> "0..1" Adres : heeft

abstract class AbstractObject << Objecttype >> {
    + identificatie
    + documentdatum
    + documentnummer
    + geconstateerd
    + status
'     --
}

class Adres << extern >> {
}

class Bouwbesluit << extern >> {
}

class Bouwblok << Objecttype >> {
'     ..//verplicht//..
'     ..//vrijwillig//..
'     --
    Grootst mogelijke geheel van aaneengesloten gebouwen.
}

class Bouwlaag << Objecttype >> << vrijwillig >> {
    + geometrie
    + verdiepingsaanduiding [1..1]
    --
    Grootste aaneengesloten gedeelte van een gebouw met dezelfde vloerhoogte.
}

class Bouwwerk << Objecttype >> {
'     ..//verplicht//..
    + bouwgeometrie [0..1]
    + bouwjaar [1..1]
'     + opleverdatum [1..1]
    + sloopgeometrie [0..*]
    + typeBouwwerk: TypeBouwwerk [1..*]
    + typeConstructie: TypeConstructie [1..*]
'     + vigerendBouwbesluit [1..1]
'     ..//vrijwillig//..
    --
    Grootst mogelijke geheel van een aaneengesloten en in één keer gerealiseerde bouwkundige constructie, ongeacht de bereikbaarheid binnendoor.
}

class Gebouw << Objecttype >> {
'     ..//verplicht//..
    + typeGebouw: TypeGebouw [1..*]
'     ..//vrijwillig//..
    --
    Grootst mogelijke homogene en tezamen duurzaam met de aarde verbonden geheel van aaneengesloten bouwwerken waarop de kleinst mogelijke verscheidenheid van attribuutwaarden integraal van toepassing is, ongeacht de bereikbaarheid binnendoor.
}

class Gebruikseenheid << Objecttype >> {
    + feitelijkGebruik
    + gebruiksdoel: Gebruiksdoel [1..*]
    + vergundGebruik
    --
    Kleinste ondeelbare samenstel van alle verblijfseenheden, gebouwen en voorzieningen die als geheel worden gebruikt.
}

class "IFC-model" << extern >> {
'     https://hetnationaalbimplatform.nl/upload/documents/RVB_BIM_Norm_v1.1.pdf
}

class Toegang << Objecttype >> {
    + geometrie
    + toegankelijkheid
    --
    Deur of andere voorziening die toegang geeft tot een verblijfseenheid.
}

class Vastgoed << extern >> {
}

class Verblijfseenheid << Objecttype >> {
    + geometrie
    + oppervlakte
    --
    Kleinste binnen een bouwblok gelegen aaneengesloten eenheid van gebruik die volledig binnendoor bereikbaar is en ontsloten wordt via een eigen toegang vanaf de openbare weg, een erf of een gedeelde verkeersruimte, onderwerp kan zijn van goederenrechtelijke rechtshandelingen en in functioneel opzicht zelfstandig is.
}

class Voorziening << Objecttype >> {
'     + gedeeldeVoorziening
'     + geometrie
    + typeVoorziening: TypeVoorziening
    --
    Kleinste geheel van een installatie of andere voorziening die relevant is voor een of meer gebruikseenheden.
}

@enduml
