@startuml

' --------v-v-v-v-v-v-v-v--------
' https://www.rijkshuisstijl.nl/organisatiespecifieke-richtlijnen/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/deelidentiteit-kerndepartement-bzk
' https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
'
' # Communicatiekleuren
' Het kerndepartement van BZK heeft uit het kleurenpalet van de rijkshuisstijl drie kleuren (elk met tint1 / tint2) gekozen:
' - Rijksoverheid hemelblauw #007bc7 (#b2d7ee/#d9ebf7)
' - Rijksoverheid rood #d52b1e (#f2bfbb/#f9dfdd)
' - Rijksoverheid groen #39870c (#c3dbb6/#e1eddb)
' Het gebruik van deze kleuren in combinatie met veel wit wordt gestimuleerd.
'
' # Tinten voor achtergrondkaders, grafieken en tabellen
' Voor achtergrondkaders, grafieken en tabellen kunnen 7 neutrale grijstinten of tinten van een communicatiekleur in stappen van 20% worden toegepast. Voor tekstachtergrond wordt grijstint1 of communicatiekleur tint2 aanbevolen om aan de contrasteisen voor een goede leesbaarheid te voldoen.
'
' Rijksoverheid grijs 1 #f3f3f3
' Rijksoverheid grijs 2 #e6e6e6
' Rijksoverheid grijs 3 #cccccc
' Rijksoverheid grijs 4 #b4b4b4
' Rijksoverheid grijs 5 #999999
' Rijksoverheid grijs 6 #696969
' Rijksoverheid grijs 7 #535353

' --------^-^-^-^-^-^-^-^--------

skinparam defaultFontColor black
skinparam defaultFontName Lucida Sans
skinparam defaultFontSize 11
skinparam defaultFontStyle normal
skinparam defaultMonospacedFontName Lucida Sans Typewriter
' skinparam defaultTextAlignment left
' skinparam lineType ortho
' skinparam lineType polyline
skinparam shadowing false
skinparam wrapWidth 165

skinparam class {
    ArrowColor #39870c
    ArrowFontSize 10
'     ArrowTextAlignment center
    ArrowThickness 1.5
'     AttributeFontColor #000000
    AttributeIconSize 0
    BackgroundColor #ffffff
    BorderColor #007bc7
    BorderThickness 2
    FontColor #007bc7
    FontSize 12
    FontStyle bold
'     StereotypeFontStyle italic
'     StereotypeFontColor #000000
}

skinparam class<<extern>> {
    AttributeFontColor #b4b4b4
    BorderColor #b4b4b4
    FontColor #b4b4b4
    StereotypeFontColor #b4b4b4
}

skinparam class<<vrijwillig>> {
    BorderThickness 1
    FontStyle normal
}

skinparam note {
    BackgroundColor #fdf6bb
    BorderColor #f9e11e
    FontColor #007bc7
}

skinparam package {
    BackgroundColor #f3f3f3
    BorderColor #d52b1e
    FontColor #d52b1e
    FontSize 12
    FontStyle bold
    Style rectangle
}

skinparam package<< subpackage >> {
    BackgroundColor #e6e6e6
    BorderColor #e6e6e6
    FontStyle normal
}

hide circle

hide empty members

hide stereotype

' hide AbstractObject


' =================================================================================================


package "FUNCTIE" {
    class Verblijfsobject {
    }
    class WOZ-object {
    }
}

package "FYSIEK" {
    class Bouwlaag {
    }
    class Constructie {
    }
    class Gebouw {
    }
    class Gebouwdeel {
    }
    class Gebouwinstallatie {
    }
    class Voorziening {
    }
    together {
        class Bouwlaag {
        }
        class Gebouwinstallatie {
        }
        class Voorziening {
        }
    }
}

Verblijfsobject -- Gebouw : ligt\nin >
Verblijfsobject -- Gebouwdeel : ligt\nin >
Gebouw -left- Gebouwdeel : bestaat\nuit >
Gebouw -- Bouwlaag : bestaat\nuit >
Gebouwdeel -- Bouwlaag : bestaat\nuit >
"WOZ-object" .. Gebouw
"WOZ-object" .. Gebouwdeel
"WOZ-object" .left. Verblijfsobject
"WOZ-object" .. Constructie

class Bouwlaag << Objecttype >> << vrijwillig >> {
}

class Constructie {
}

class Gebouw << Objecttype >> {
}

class Gebouwdeel << Objecttype >> {
}

class Gebouwinstallatie {
}

class Verblijfsobject << Objecttype >> {
}

class WOZ-object << Objecttype >> << extern >> << vrijwillig >> {
}

@enduml
