@startuml

' skinparam linetype ortho
' skinparam linetype polyline

skinparam class {
    BackgroundColor #ffffff
    BorderColor #008dc9
    ArrowColor #00387d
    ArrowThickness 1.5
}

hide empty members

hide circle

hide stereotype

package "Waardelijsten" <<rectangle>> #ededed {
    ' https://www.groephuyzentruyt.be/blog/de-verschillende-bouwmethodes
    class TypeConstructie << Referentielijst >> {
        beton
        houtskelet
        metselwerk
        prefab
        staalstructuur
    }

    class TypeVoorziening << Referentielijst >> {
        atelier/hobbyruimte
        badkamer
        balkon
        berging
        carport
        dakkapel
        dakopbouw
        dakterras
        garage
        keuken
        kelder
        meterkast
        serre
        souterrain
        terras
        toilet
        toren
        trap
        zolder
        zwembad
        --
        Gebaseerd op o.a. CityGML
        2.0 BuildingInstallation
        function en Room function.
    }

'     class TypeMetagegeven << Referentielijst >> {
'         in onderzoek
'         accuraatheid
'         bewerkingsmethode
'         inwinningsmethode
'     }

    class Gebruiksdoel << Referentielijst >> {
        bijeenkomstfunctie
        celfunctie
        gezondheidszorgfunctie
        industriefunctie
        kantoorfunctie
        logiesfunctie
        onderwijsfunctie
        sportfunctie
        winkelfunctie
        woonfunctie
        overige gebruiksfunctie
        --
        Overgenomen van BAG en
        art. 1.1 van Bouwbesluit 2012.
    }

    class TypeGebouw << Referentielijst >> {
' http://inspire.ec.europa.eu/codelist/BuildingNatureValue
'         boog
'         bunker
'         dam
'         grotgebouw
'         kapel
'         kas
'         kasteel
'         kerk
'         moskee
'         opslagtank
'         overkapping
'         schuur
'         silo
'         stadion
'         synagoge
'         tempel
'         toren
'         vuurtoren
'         windmolen
'         windturbine
'         zonnescherm
'         --
'         Overgenomen van INSPIRE
'         BuildingNatureValue.
'
        bezoekerscentrum
        boortoren
        brandtoren
        brandweerkazerne
        bunker
        crematorium
        dok
        elektriciteitscentrale
        fabriek
        fort
        gemaal
        gemeentehuis
        gevangenis
        hotel
        huizenblok
        kapel
        kas, warenhuis
        kasteel
        kerk
        kerncentrale, kernreactor
        kliniek, inrichting, sanatorium
        klokkentoren
        klooster, abdij
        koeltoren
        koepel
        kunstijsbaan
        lichttoren
        luchtwachttoren
        manege
        markant gebouw
        militair gebouw
        moskee
        museum
        observatorium
        overig religieus gebouw
        paleis
        parkeerdak, parkeerdek, parkeergarage
        peilmeetstation
        politiebureau
        pompstation
        postkantoor
        psychiatrisch centrum
        radarpost
        radartoren
        radiotoren, televisietoren
        ziekenhuis,
        psychiatrisch
        recreatiecentrum
        reddingboothuisje
        remise
        ruïne
        schaapskooi
        school
        schoorsteen
        silo
        sporthal
        stadion
        stadskantoor, hulpsecretarie
        stationsgebouw
        synagoge
        tank
        tankstation
        telecommunicatietoren
        tol
        toren
        transformatorstation
        uitzichttoren
        universiteit
        veiling
        verkeerstoren
        vuurtoren
        waterradmolen
        watertoren
        wegrestaurant
        werf
        windmolen
        windmolen: korenmolen
        windmolen: watermolen
        windturbine
        zendtoren
        ziekenhuis
        zwembad
        overig
        --
        Overgenomen van Basisregistratie
        Topografie: Catalogus en
        Productspecificaties,
        versie 1.2.0.1, 8 juli 2019.
    }
}
@enduml
