@startuml

' skinparam linetype ortho
' skinparam linetype polyline

' --------v-v-v-v-v-v-v-v--------
' https://www.rijkshuisstijl.nl/organisatiespecifieke-richtlijnen/ministerie-van-binnenlandse-zaken-en-koninkrijksrelaties/deelidentiteit-kerndepartement-bzk
' https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
'
' # Communicatiekleuren
' Het kerndepartement van BZK heeft uit het kleurenpalet van de rijkshuisstijl drie kleuren (elk met tint1 / tint2) gekozen:
' - Rijksoverheid hemelblauw #007bc7 (#b2d7ee/#d9ebf7)
' - Rijksoverheid rood #d52b1e (#f2bfbb/#f9dfdd)
' - Rijksoverheid groen #39870c (#c3dbb6/#e1eddb)
' Het gebruik van deze kleuren in combinatie met veel wit wordt gestimuleerd.
'
' # Tinten voor achtergrondkaders, grafieken en tabellen
' Voor achtergrondkaders, grafieken en tabellen kunnen 7 neutrale grijstinten of tinten van een communicatiekleur in stappen van 20% worden toegepast. Voor tekstachtergrond wordt grijstint1 of communicatiekleur tint2 aanbevolen om aan de contrasteisen voor een goede leesbaarheid te voldoen.
'
' Rijksoverheid grijs 1 #f3f3f3
' Rijksoverheid grijs 2 #e6e6e6
' Rijksoverheid grijs 3 #cccccc
' Rijksoverheid grijs 4 #b4b4b4
' Rijksoverheid grijs 5 #999999
' Rijksoverheid grijs 6 #696969
' Rijksoverheid grijs 7 #535353

' skinparam linetype ortho
' skinparam linetype polyline
' --------^-^-^-^-^-^-^-^--------

skinparam WrapWidth 220

skinparam Shadowing false

skinparam classAttributeIconSize 0

skinparam class {
    ArrowColor #39870c
'     ArrowMessageAlignment center
    ArrowThickness 1.5
    BackgroundColor #ffffff
    BorderColor #007bc7
    BorderColor<<extern>> #999999
    FontColor<<extern>> #999999
'     FontName RijksoverheidSansText
'     StereotypeFontStyle italic
}

skinparam note {
    BackgroundColor #fdf6bb
    BorderColor #f9e11e
    FontColor #01689b
'     FontName RijksoverheidSansText
}

skinparam package {
    BorderColor #d52b1e
    FontColor #d52b1e
'     FontName RijksoverheidSansText
    FontStyle normal
    Style rectangle
}

hide empty members

hide circle

hide stereotype

together {
    class TypeConstructie
    class TypeVoorziening
'     class TypeMetagegeven
    class Gebruiksdoel
'     class TypeGebouw
}

package "Waardelijsten" <<rectangle>> #ededed {
    ' https://www.groephuyzentruyt.be/blog/de-verschillende-bouwmethodes
    class TypeConstructie << Referentielijst >> {
        + beton
        + houtskelet
        + metselwerk
        + prefab
        + staalstructuur
    }

    class TypeVoorziening << Referentielijst >> {
        + atelier/hobbyruimte
        + badkamer
        + balkon
        + berging
        + carport
        + dakkapel
        + dakopbouw
        + dakterras
        + garage
        + kelder
        + keuken
        + meterkast
        + serre
        + souterrain
        + terras
        + toilet
        + toren
        + trap
        + zolder
        + zwembad
        --
        Bronnen: CityGML 2.0 BuildingInstallation function; CityGML 2.0 Room function
    }

'     class TypeMetagegeven << Referentielijst >> {
'         accuraatheid
'         bewerkingsmethode
'         in onderzoek
'         inwinningsmethode
'     }

    class Gebruiksdoel << Referentielijst >> {
        + bijeenkomstfunctie
        + celfunctie
        + gezondheidszorgfunctie
        + industriefunctie
        + kantoorfunctie
        + logiesfunctie
        + onderwijsfunctie
        + sportfunctie
        + winkelfunctie
        + woonfunctie
        + overige gebruiksfunctie
        --
        Bronnen: BAG; Bouwbesluit 2012
    }

    class TypeGebouw << Referentielijst >> {
' http://inspire.ec.europa.eu/codelist/BuildingNatureValue
'         boog
'         bunker
'         dam
'         grotgebouw
'         kapel
'         kas
'         kasteel
'         kerk
'         moskee
'         opslagtank
'         overkapping
'         schuur
'         silo
'         stadion
'         synagoge
'         tempel
'         toren
'         vuurtoren
'         windmolen
'         windturbine
'         zonnescherm
'         --
'         Bron: INSPIRE BuildingNatureValue
'
        + bezoekerscentrum
        + boortoren
        + brandtoren
        + brandweerkazerne
        + bunker
        + crematorium
        + dok
        + elektriciteitscentrale
        + fabriek
        + fort
        + gemaal
        + gemeentehuis
        + gevangenis
        + hotel
        + huizenblok
        + kapel
        + kas, warenhuis
        + kasteel
        + kerk
        + kerncentrale, kernreactor
        + kliniek, inrichting, sanatorium
        + klokkentoren
        + klooster, abdij
        + koeltoren
        + koepel
        + kunstijsbaan
        + lichttoren
        + luchtwachttoren
        + manege
        + markant gebouw
        + militair gebouw
        + moskee
        + museum
        + observatorium
        + overig religieus gebouw
        + paleis
        + parkeerdak, parkeerdek, parkeergarage
        + peilmeetstation
        + politiebureau
        + pompstation
        + postkantoor
        + psychiatrisch ziekenhuis, psychiatrisch centrum
        + radarpost
        + radartoren
        + radiotoren, televisietoren
        + recreatiecentrum
        + reddingboothuisje
        + remise
        + ruïne
        + schaapskooi
        + school
        + schoorsteen
        + silo
        + sporthal
        + stadion
        + stadskantoor, hulpsecretarie
        + stationsgebouw
        + synagoge
        + tank
        + tankstation
        + telecommunicatietoren
        + tol
        + toren
        + transformatorstation
        + uitzichttoren
        + universiteit
        + veiling
        + verkeerstoren
        + vuurtoren
        + waterradmolen
        + watertoren
        + wegrestaurant
        + werf
        + windmolen
        + windmolen: korenmolen
        + windmolen: watermolen
        + windturbine
        + zendtoren
        + ziekenhuis
        + zwembad
        + overig
        --
        Bron: Basisregistratie Topografie: Catalogus en Productspecificaties, versie 1.2.0.1, 8 juli 2019
    }

note bottom of TypeGebouw : Niet-fysieke kenmerken schrappen uit de waardelijst van TypeGebouw

}
@enduml
